spring:
  application:
    name: pocketmind-server
  data:
    redis:
      host: localhost
      port: 6379
  ai:
    dashscope:
      api-key: your_key_here
      chat:
        options:
          model: qwen-turbo
          temperature: 0.7
    alibaba:
      toolcalling:
        baidu:
          search:
            enabled: true
        tavilysearch:
          api-key: your_key_here
          enabled: true
        jinacrawler:
          enabled: true
          api-key: your_key_here

# 日志配置
logging:
  level:
    com.example: debug