spring:
  application:
    name: pocketmind-server
  data:
    redis:
      host: localhost
      port: 6379
  ai:
    dashscope:
      api-key: sk-e82d13dcb4ec42d79a95e26262220f51
      chat:
        options:
          model: qwen-turbo
          temperature: 0.7
    alibaba:
      toolcalling:
        baidu:
          search:
            enabled: true
        tavilysearch:
          api-key: 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
          enabled: true
        jinacrawler:
          enabled: true
          api-key: jina_6dae77e988d14583b581209b3205eaeaqnJ7QnK8iqeolsV9k11MTnyyIVLB
  mail:
    host: smtp.qq.com
    port: 465
    username: 1624475081@qq.com
    password: gyfiybzapiamjfdf
    protocol: smtp
    properties: # 下面要用properties的写法才可以生效
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true  # 启用SSL
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    #      mail.debug: true  # 开启调试日志
    default-encoding: utf-8
# 日志配置
logging:
  level:
    com.example: debug